
# tap repositories and their packages

tap homebrew/core
brew act
brew aom
brew atk
brew autoconf
brew automake
brew bdw-gc
brew berkeley-db
brew bitwarden-cli
brew boost
brew brotli
brew c-ares
brew cairo
brew coreutils
brew dav1d
brew dfu-util
brew docbook
brew docbook-xsl
brew docker
brew dos2unix
brew dtc
brew ext4fuse
brew fd
brew ffmpeg
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew fzf
brew gcc
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghostscript
brew giflib
brew git
brew glib
brew glow
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnupg
brew gnutls
brew gobject-introspection
brew graphite2
brew gtk+
brew guile
brew harfbuzz
brew hashcat
brew hicolor-icon-theme
brew htop
brew icu4c
brew ilmbase
brew imagemagick
brew imath
brew isl
brew jansson
brew jbig2dec
brew jemalloc
brew jpeg
brew jq
brew lame
brew leptonica
brew libarchive
brew libass
brew libassuan
brew libb2
brew libbluray
brew libde265
brew libev
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libheif
brew libidn
brew libidn2
brew libksba
brew liblqr
brew libmpc
brew libogg
brew libomp
brew libpng
brew libpthread-stubs
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvorbis
brew libvpx
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxml2
brew libxrender
brew libyaml
brew little-cms2
brew llvm
brew luajit-openresty
brew luv
brew lz4
brew lzo
brew m4
brew mas
brew maven
brew mpdecimal
brew mpfr
brew msgpack
brew ncdu
brew ncurses
brew neofetch
brew neovim
brew nettle
brew nghttp2
brew nginx
brew ninja
brew nmap
brew node
brew npth
brew oniguruma
brew opencore-amr
brew openexr
brew openjdk
brew openjpeg
brew openssl@1.1
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew perl
brew pinentry
brew pinentry-mac
brew pixman
brew pkg-config
brew popt
brew pv
brew python@3.8
brew python@3.9
brew rav1e
brew readline
brew ripgrep
brew rsync
brew rubberband
brew ruby
brew screenresolution
brew sdl2
brew shared-mime-info
brew snappy
brew speex
brew sqlite
brew srt
brew tcl-tk
brew telnet
brew tesseract
brew texinfo
brew thefuck
brew theora
brew tree-sitter
brew unbound
brew unibilium
brew watch
brew webp
brew wget
brew x264
brew x265
brew xmlto
brew xorgproto
brew xvid
brew xxhash
brew xz
brew yadm
brew yarn
brew youtube-dl
brew zeromq
brew zimg
brew zsh
brew zstd

tap homebrew/bundle

tap homebrew/cask-drivers

tap homebrew/cask-fonts

tap homebrew/cask-versions

tap homebrew/services

tap homebrew/cask
cask alfred
cask android-platform-tools
cask battle-net
cask bitwarden
cask blender
cask calibre
cask discord
cask firefox
cask gimp
cask keybase
cask kicad
cask native-access
cask nvidia-geforce-now
cask osxfuse
cask powder
cask steam
cask telegram
cask textual
cask ti-connect-ce
cask tor-browser
cask ultimaker-cura
cask vial
cask visual-studio-code
cask vlc
cask zerotier-one
cask zoom

tap adoptopenjdk/openjdk

tap buo/cask-upgrade

tap osx-cross/arm
brew arm-gcc-bin@10

tap osx-cross/avr

tap purduesigbots/pros

tap railwaycat/emacsmacport
brew emacs-mac

tap rcmdnk/file
brew brew-file

tap riscv/riscv
brew riscv-gnu-toolchain
brew riscv-isa-sim
brew riscv-pk
brew riscv-tools

# App Store applications
appstore 1440147259  AdGuard for Safari  (1.10.4)
appstore 424390742   Compressor          (4.5.4)
appstore 424389933   Final Cut Pro       (10.5.4)
appstore 409183694   Keynote             (11.1)
appstore 634148309   Logic Pro           (10.6.3)
appstore 409203825   Numbers             (11.1)
appstore 409201541   Pages               (11.1)
appstore 425424353   The Unarchiver      (4.3.3)
appstore 497799835   Xcode               (13.0)
